# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

branch_bound_SetCover_cpp <- function(Z, R) {
    .Call('_Algo_branch_bound_SetCover_cpp', PACKAGE = 'Algo', Z, R)
}

greedy_SetCover_cpp <- function(Z, R) {
    .Call('_Algo_greedy_SetCover_cpp', PACKAGE = 'Algo', Z, R)
}

naive_SetCover_cpp <- function(Z, R) {
    .Call('_Algo_naive_SetCover_cpp', PACKAGE = 'Algo', Z, R)
}

